# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"&\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t2E\n\x11SentimentAnalyzer\x12\x30\n\x07\x41nalyze\x12\x11.SentimentRequest\x1a\x12.SentimentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=19
  _globals['_SENTIMENTREQUEST']._serialized_end=51
  _globals['_SENTIMENTRESPONSE']._serialized_start=53
  _globals['_SENTIMENTRESPONSE']._serialized_end=91
  _globals['_SENTIMENTANALYZER']._serialized_start=93
  _globals['_SENTIMENTANALYZER']._serialized_end=162
# @@protoc_insertion_point(module_scope)
